### ISSUE TITLE
Theme color pallet not full appearing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/beko#1]
If we try to change the theme color pallet, it will not fully display : https://prnt.sc/uvz5d5

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
