### ISSUE TITLE
Header color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/beko#2]
The color pallets for the header's following options do not fully appear :
Header menu hover border color:https://prnt.sc/uvz7f7
Dropdown menu color: https://prnt.sc/uvz7mj
Dropdown menu hover color : https://prnt.sc/uvz7sv

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
